name: Build symbolator

on:
  push:
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v21
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Build symbolator
        run: |
          nix build --sandbox --print-build-logs .
      - name: Bundle self extracting archive
        run: |
          nix bundle --sandbox --print-build-logs .
          mv python*-symbolator symbolator-arx || true
      - name: Bundle AppImage
        run: |
          nix bundle --sandbox --print-build-logs --bundler github:ralismark/nix-appimage .
          mv python*symbolator*AppImage symbolator.AppImage
      - name: Verify AppImage
        run: |
          ./symbolator.AppImage --appimage-extract-and-run --version
      - name: Verify self extracting archive
        run: |
          ./symbolator-arx --version
