name: "Publish release"

on:
  push:
    tags:
      - "**"

permissions:
  contents: write
  pull-requests: read

jobs:
  create-release:
    name: "Create release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v21
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Build symbolator
        run: |
          nix build --sandbox --print-build-logs .
      - name: Bundle self extracting archive
        run: |
          nix bundle --sandbox --print-build-logs .
          mv symbolator symbolator-arx || true
      - name: Bundle AppImage
        run: |
          nix bundle --sandbox --print-build-logs --bundler github:ralismark/nix-appimage .
          mv symbolator*AppImage symbolator.AppImage
      - name: Verify AppImage
        run: |
          ./symbolator.AppImage --appimage-extract-and-run --version
      - name: Verify self extracting archive
        run: |
          ./symbolator-arx --version
      - name: "Determine tag"
        run: 'echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV'

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
      - name: Upload AppImage
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: symbolator-x86_64.AppImage
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload self extracting archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: symbolator-arx
          tag: ${{ github.ref }}
          overwrite: true
